{{- if not (or .Values.css_ovh .Values.css_hashicorp) }}
{{- fail "one of css_ovh or css_hashicorp must be enabled" }}
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.css_name }}
spec:
  {{- if .Values.css_condition_namespaces }}
  conditions:
    - namespaces:
{{ toYaml .Values.css_condition_namespaces | indent 6 }}
  {{- end }}
  provider:
    vault:
      {{- if or .Values.css_ovh .Values.css_hashicorp }}
      auth:
      {{- if .Values.css_ovh }}
        tokenSecretRef:
          name: {{ .Values.css_secret_id_name }}
          key: token
          namespace: {{ .Values.css_secret_id_namespace }}
      {{- end }}
      {{- if .Values.css_hashicorp }}
        appRole:
          path: approle
          roleRef:
            key: role_id
            name: {{ .Values.css_secret_id_name }}
            namespace: {{ .Values.css_secret_id_namespace }}
          secretRef:
            key: secret_id
            name: {{ .Values.css_secret_id_name }}
            namespace: {{ .Values.css_secret_id_namespace }}
      {{- end }}
      {{- end }}
      {{- if .Values.css_ca_bundle }}
      caBundle: "{{ .Values.css_ca_bundle }}"
      {{- end }}
      path: {{ .Values.css_vault_path }}
      {{- if .Values.css_vault_namespace }}
      namespace: {{ .Values.css_vault_namespace }}
      {{- end }}
      server: '{{ .Values.css_vault_server }}'
      version: v2
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
