---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.css_name }}
spec:
  {{- if .Values.css_condition_namespaces }}
  conditions:
    - namespaces:
{{ toYaml .Values.css_condition_namespaces | indent 6 }}
  {{- end }}
  provider:
    vault:
      auth:
        tokenSecretRef:
          name: {{ .Values.css_secret_id_name }}
          key: token
          namespace: {{ .Values.css_secret_id_namespace }}
      {{- if .Values.css_ca_bundle }}
      caBundle: "{{ .Values.css_ca_bundle }}"
      {{- end }}
      path: {{ .Values.css_vault_path }}
      {{- if .Values.css_vault_namespace }}
      namespace: {{ .Values.css_vault_namespace }}
      {{- end }}
      server: '{{ .Values.css_vault_server }}'
      version: v2
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
