{{- if .Values.issuer.vault.enabled }}
---
# Vault CA Bundle
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ .Values.issuer.vault.hashicorpVault.caBundleSecretRef.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.issuer.vault.hashicorpVault.caBundleSecretRef.syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
data:
  ca.crt: {{ .Values.issuer.vault.hashicorpVault.caBundleSecretRef.value | trim }}
---
# Vault AppRole Secret
{{- if .Values.css.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.vaultAppRoleSecret.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vaultAppRoleSecret.syncwave | quote }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.css.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vaultAppRoleSecret.name }}
    template:
      engineVersion: v2
      data:
        secretId: "{{ `{{ .secret_id }}` }}"
  data:
    - secretKey: secret_id
      remoteRef:
        key: {{ .Values.css.vaultSecretPath }}
        property: secret_id
{{- else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.vaultAppRoleSecret.name }}
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vaultAppRoleSecret.syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
stringData:
  secretId: {{ .Values.vaultAppRoleSecret.secret }}
{{- end }}
{{- end }}

{{- if .Values.issuer.letsencrypt.enabled }}
---
# Cloudflare API Token
{{- if .Values.css.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Values.vaultAppRoleSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.css.name }}
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.css.cloudflareSecretPath }}
        property: {{ .Values.css.cloudflareSecretProperty }}
{{- else }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
stringData:
  api-token: {{ .Values.issuer.letsencrypt.cloudflare.token }}
{{- end }}
{{- end }}
