apiVersion: apps/v1
kind: Deployment
metadata:
  name: okms-secret-fetcher-demo
  namespace: okms
spec:
  template:
    spec:
      initContainers:
        - name: fetch-okms-secret
          image: <YOUR_REGISTRY>/okms-secret-fetcher:dev
