apiVersion: v2
name: rook-ceph-operator
description: Master chart to deploy and configure ROOK Ceph Operator
version: 1.0.1
home: >-
  https://github.com/lightning-it/lab-k8s/tree/ovh/charts/rook-ceph-operator
dependencies:
  - name: rook-ceph
    repository: https://charts.rook.io/release
    version: v1.18.8
