apiVersion: v2
name: external-secrets-operator
description: Master chart to deploy and configure External Secrets operator
version: 1.0.0
home: >-
  https://github.com/lightning-it/lab-k8s/tree/ovh/charts/external-secrets-operator
dependencies:
  - name: helper-operator
    repository: https://github.com/lightning-it/helm-charts/charts/helper-operator
    version: 0.0.18
  - condition: helper-status-checker.enabled
    name: helper-status-checker
    repository: https://github.com/lightning-it/helm-charts/charts/helper-status-checker
    version: 0.0.18
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
